%YAML 1.2
---
user_files: user_files
server:
    protocol: http
    hostname: localhost
    port: 3000
    path: ''
log:
    appenders:
        - type: console
        - type: file
          filename: logs/tfm.log
          maxLogSize: 100000
          backups: 5
    levels:
        '[all]': 'TRACE'
